version: "3.8"

services:
  postgresdb:
    image: postgres:14.1
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
  app:
    depends_on:
      - postgresdb
    image: mystidreamer/university-test-project-app
    build: .
    env_file: ./.env
    ports:
      - 8081:8080

    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:postgresql://postgresdb:$POSTGRES_DOCKER_PORT/$POSTGRES_DB?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "$POSTGRES_USER",
      "spring.datasource.password" : "$POSTGRES_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "create"
      }'
